### PR TITLE
Update to front end

### PR DESCRIPTION
**Pull request by Awesomaster**
Addition of some basic css for colouring and storing those value in variables for ease of use. Added button for copy to clipboard of result. The order of the css file probably needs more organising.

### CODE REVIEW

**Review by Abdi-VGW — APPROVED** [review]
Looks good to me!

**Comment by Awesomaster** [comment]
image_of_updates

**Review by Abdi-VGW — APPROVED** [review]
lgtm

**Review by Abdi-Isse — APPROVED** [review]
lgtm

**Pull request merged**
